### PR TITLE
Extended reflection probe options

### PR DESCRIPTION
**Pull request by klmcdorm**
With olmod and the community OLE now supporting lava particle effects, there have been times where I wanted to use them while also placing custom reflection probes. Because both of these things use Box Lava trigger entities, this pull request adds options to filter which triggers get converted into reflection probes. The options I added are:
* All Box Lava triggers
* All Box Lava Alien triggers
* Box Lava triggers with OneTime set
* Box Lava Alien triggers with OneTime set

But I also changed these options to always remove the default probes.

Please let me know what you think!

### CODE REVIEW

**Comment by arbruijn** [comment]
Thank you!

Now that we have the editor source, it might be possible to improve on this by adding a new TriggerSubType in the editor for the reflection probe (BOX_REFLECTION_PROBE?) Then LevelPost could unconditionally convert that subtype.
Maybe even convert the reflection probe in the editor itself, not sure how easy that is.

Is that something you can try?

**Comment by klmcdorm** [comment]
I can try adding that to the editor. I had been avoiding that because it will change the .overload format a little and possibly break compatibility with the original editor, but maybe that already happened with the user doors.

**Comment by arbruijn** [comment]
Ah I hadn't thought of that. But it seems unlikely to me anybody would use the original editor after using the community version.

**Comment by klmcdorm** [comment]
I've created [a pull request for the editor](https://github.com/overload-development-community/OverloadLevelEditor/pull/52) which adds a reflection probe subtype and is converted by the editor.

**Comment by arbruijn** [comment]
Very nice, thanks!

That means this PR can be closed, right?

**Comment by klmcdorm** [comment]
If you don't want to add this to LevelPost, it can be closed.

**Comment by arbruijn** [comment]
I think these extra conversion rules are no longer needed now that it's possible to add custom probes directly in the editor.

**Pull request closed without merging**
